---
title: "Compare algorithms"
author: "Katsuhiro Komatsu"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
gc()
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library("magrittr")
library("ggplot2")
library("foreach")
library("Dispatching")

```





```{r}
eq <- readRDS(here::here("output/estimate_structural_parameters/equilibrium_data_distance_IV.RDS"))
parameters <- eq$parameters
spec <- eq$spec

data <- construct_hypothetical_market_nonrandom(eq)
ownership <- diag(length(data$id_unique))
out <- solve_equilibrium_single_market_wrapper(data, ownership, parameters, spec, cpp = T)
data$price <- out[, 2:3]

```


# Equilibrium without constraints

```{r}

result_table <- out[, c("wage", "fee", "s_W", "s_F")] %>% as.data.frame()
result_table$margin <- log(result_table$fee) - log(result_table$wage)
result_table <- result_table[, c("wage", "fee", "margin", "s_W", "s_F")]

result_table <- as.data.frame(result_table)
result_table[, 1:3] <- round(result_table[, 1:3], digits = 2)
result_table[, 4:5] <- round(result_table[, 4:5], digits = 5)
rownames(result_table) <- c("Establishment 1", "Establishment 2")
colnames(result_table) <- c("Wage", "Fee", "Margin", "Worker share", "Client firm share")
  
  
result_table %>%
  kableExtra::kbl(
    format = "html",
    booktabs = TRUE,
    align = rep("r", 5),
    linesep = ""
  ) %>% 
  kableExtra::kable_classic(full_width = F, html_font = "Cambria")
```


# Compute FOC error

- Compute FOC error $\frac{\partial \Pi_i}{\partial w_i}/Q_i$ and $\frac{\partial \Pi_i}{\partial f_i}/Q_i$ 
  - Represent how much 1K yen change in price leads to a change in per-match profit.



```{r}
margin_upper_bound_vec <- c(0.7, 0.6, 0.5, 0.4, 0.3, 0.2)
list_of_equilibrium <- list()
wage_lb <- NULL
cpp <- TRUE

```



```{r}
make_fig_w <- function(data_cf){
  
  data_cf %>% 
  dplyr::distinct() %>% 
  ggplot(
    aes(
      x = margin_constraint,
      y = abs(foc_error_w),
      color = factor(id_unique)
    )
  ) +
  geom_point() +
  geom_line() +
  labs(
    x = "Margin constraint",
    y = "FOC error (wage)",
    color = "Establishment"
  ) +
  scale_x_reverse() +
  scale_color_viridis_d(end = 0.95) +
  theme_classic() 
}


make_fig_f <- function(data_cf){
  
  data_cf %>% 
  dplyr::distinct() %>% 
  ggplot(
    aes(
      x = margin_constraint,
      y = abs(foc_error_f),
      color = factor(id_unique)
    )
  ) +
  geom_point() +
  geom_line() +
  labs(
    x = "Margin constraint",
    y = "FOC error (fee)",
    color = "Establishment"
  ) +
  scale_x_reverse() +
  scale_color_viridis_d(end = 0.95) +
  theme_classic()
  
}






```


# {.tabset}

## Nelder-Mead

```{r}

opts <- list(
  algorithm = "NLOPT_LN_NELDERMEAD",
  maxeval = 1e+6,
  xtol_rel = 1e-6
)


for (j in 1:length(margin_upper_bound_vec)){
  
  margin_upper_bound <- margin_upper_bound_vec[j]
  eq_j <- compute_equilibrium_with_margin_constraint_single_market(data, ownership, margin_upper_bound, parameters, spec = spec, cpp = cpp, wage_lb = wage_lb, opts = opts)
  eq_j$margin_constraint <- margin_upper_bound
  
  list_of_equilibrium[[j]] <- eq_j
  
}

data_cf <- do.call("rbind", list_of_equilibrium)

make_fig_w(data_cf)
make_fig_f(data_cf)


data_cf %>% 
  dplyr::select(margin_constraint, id_unique, wage, fee, convergence, multiplier) %>% 
  round(digits = 5)

```

### Strict tolrerance
- xtol_rel = 1e-6 in default. Set xtol_rel = 1e-10 here.

```{r}

opts <- list(
  algorithm = "NLOPT_LN_NELDERMEAD",
  maxeval = 1e+6,
  xtol_rel = 1e-10
)


for (j in 1:length(margin_upper_bound_vec)){
  
  margin_upper_bound <- margin_upper_bound_vec[j]
  eq_j <- compute_equilibrium_with_margin_constraint_single_market(data, ownership, margin_upper_bound, parameters, spec = spec, cpp = cpp, wage_lb = wage_lb, opts = opts)
  eq_j$margin_constraint <- margin_upper_bound
  
  list_of_equilibrium[[j]] <- eq_j
  
}

data_cf <- do.call("rbind", list_of_equilibrium)

make_fig_w(data_cf)
make_fig_f(data_cf)

data_cf %>% 
  dplyr::select(margin_constraint, id_unique, wage, fee, convergence, multiplier) %>% 
  round(digits = 5)

```


## LBFGS

```{r}

opts <- list(
  algorithm = "NLOPT_LD_LBFGS",
  maxeval = 1e+6,
  xtol_rel = 1e-6
)


for (j in 1:length(margin_upper_bound_vec)){
  
  margin_upper_bound <- margin_upper_bound_vec[j]
  eq_j <- compute_equilibrium_with_margin_constraint_single_market(data, ownership, margin_upper_bound, parameters, spec = spec, cpp = cpp, wage_lb = wage_lb, opts = opts)
  eq_j$margin_constraint <- margin_upper_bound
    
  list_of_equilibrium[[j]] <- eq_j
  
}

data_cf <- do.call("rbind", list_of_equilibrium)

make_fig_w(data_cf)
make_fig_f(data_cf)

data_cf %>% 
  dplyr::select(margin_constraint, id_unique, wage, fee, convergence, multiplier) %>% 
  round(digits = 5)

```

## SLSQP


```{r}

opts <- list(
  algorithm = "NLOPT_LD_SLSQP",
  maxeval = 1e+6,
  xtol_rel = 1e-6
)


for (j in 1:length(margin_upper_bound_vec)){
  
  margin_upper_bound <- margin_upper_bound_vec[j]
  eq_j <- compute_equilibrium_with_margin_constraint_single_market(data, ownership, margin_upper_bound, parameters, spec = spec, cpp = cpp, wage_lb = wage_lb, opts = opts)
  eq_j$margin_constraint <- margin_upper_bound

  
  list_of_equilibrium[[j]] <- eq_j
  
}

data_cf <- do.call("rbind", list_of_equilibrium)

make_fig_w(data_cf)
make_fig_f(data_cf)

data_cf %>% 
  dplyr::select(margin_constraint, id_unique, wage, fee, convergence, multiplier) %>% 
  round(digits = 5)

```




