---
title: "report_data_counterfactual_maximum_margin"
author: "Daisy Dan Song"
date: "2025-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
  )
rm(list = ls())
library(Dispatching)
library(foreach)
library(magrittr)
library(codetools)
library(ggplot2)
library(kableExtra)
```

# import solved equilibrium
```{r}
equilibrium <-
  readRDS(
    file = "output/multihome/estimate_data/equilibrium_updated_constrained.rds" %>%
    here::here()
  )
updated_ownership <- 
  readRDS(
    file = "output/multihome/make_equilibrium_nationwide_top5_from_data/updated_ownership_matrix.rds" %>%
    here::here()
  )

equilibrium$constant$use_exp <- FALSE
```

# update ownership 
```{r}
for (
  t in seq_along(equilibrium$exogenous)
) {
  for (
    j in seq_along(equilibrium$exogenous[[t]])
  ){
    equilibrium$exogenous[[t]][[j]]$owner <- updated_ownership[[t]][[j]]$owner 
  }
}
```

# check initial foc without constraint
```{r}
df <-
  check_equilibrium(
    equilibrium = equilibrium
  )
summary(df)
```


# Counterfactual Analysis {.tabset}

## maximum margin {.tabset}
```{r, cache=TRUE}

counterfactual <- 
  evaluate_counterfactual_maximum_margin_tj(
    t = t,
    j = j,
    equilibrium = equilibrium,
    solver = "nleqslv",
    multistart = 20
  )
```


```{r}
counterfactual_update <- 
  counterfactual %>%
  dplyr::group_by(
    maximum_markup,
    i
  ) %>%
  dplyr::mutate(
    dplyr::across(
      c(
        s_w,
        s_f,
        profit_ths,
        surplus_w,
        surplus_f
      ),
      sum
    )
  ) %>%
  dplyr::mutate(
  dplyr::across(
    c(
      augmented_foc_w,
      augmented_foc_f,
      foc_w,
      foc_f,
      complementarity,
      m,
      eta_f,
      meeting_probability_w,
      meeting_probability_f,
      c_w,
      c_f,
      f,
      w
    ),
    mean
  )
  ) %>%
  dplyr::ungroup() %>%
  dplyr::distinct(
    maximum_markup,
    i,
    .keep_all = TRUE
  )
```

### table 
```{r, results = "asis"}
counterfactual %>%
  dplyr::arrange(
    i,
    maximum_markup
  ) %>%
  kbl() %>%
  kable_styling()
```

### outside/private/fringe {.tabset}
```{r, results = "asis"}
p <- 
  plot_counterfactual_maximum_margin_outside(
    counterfactual = counterfactual
  )
```



### inside {.tabset}
```{r, results = "asis"}
p <- 
  plot_counterfactual_maximum_margin_inside(
    counterfactual = counterfactual
  )
```
```