---
title: "report_data_counterfactual_minimum_wage"
author: "Daisy Dan Song"
date: "2025-01-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
  )
rm(list = ls())
library(Dispatching)
library(foreach)
library(magrittr)
library(codetools)
library(ggplot2)
library(kableExtra)
```

# import solved equilibrium
```{r}
equilibrium <-
  readRDS(
    file = "output/multihome/estimate_data/equilibrium_updated_constrained.rds" %>%
    here::here()
  )
updated_ownership <- 
  readRDS(
    file = "output/multihome/make_equilibrium_nationwide_top5_from_data/updated_ownership_matrix.rds" %>%
    here::here()
  )

equilibrium$constant$use_exp <- FALSE
```

# update ownership 
```{r}
for (
  t in seq_along(equilibrium$exogenous)
) {
  for (
    j in seq_along(equilibrium$exogenous[[t]])
  ){
    equilibrium$exogenous[[t]][[j]]$owner <- updated_ownership[[t]][[j]]$owner 
  }
}
```

# counterfactual with minimum wage 
## minimum wage {.tabset}
```{r, cache=TRUE}
counterfactual <- 
  evaluate_counterfactual_minimum_wage(
    equilibrium = equilibrium,
    solver = "nleqslv",
    multistart = 20
  )
```

### table 
```{r, results = "asis"}
counterfactual %>%
  dplyr::arrange(
    i,
    minimum_wage
  ) %>%
  kbl() %>%
  kable_styling()
```

### outside market {.tabset}
```{r, results = "asis"}

p <- 
  plot_counterfactual_minimum_wage_outside(
    counterfactual = counterfactual
  )
p
```

### inside market {.tabset}
```{r, results = "asis"}
p <- 
  plot_counterfactual_minimum_wage_inside(
    counterfactual = counterfactual
  )
p
```



