---
title: "report_data_counterfactual_minimum_wage_iteration"
author: "Daisy Dan Song"
date: "2025-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
  )
rm(list = ls())
library(Dispatching)
library(foreach)
library(magrittr)
library(codetools)
library(ggplot2)
library(kableExtra)
```

# import solved equilibrium
```{r}
equilibrium <-
  readRDS(
    file = "output/multihome/estimate_data/equilibrium_updated.rds" %>%
    here::here()
  )

# update the mu shape
equilibrium <-
  update_mu(
    equilibrium = equilibrium,
    parameter = equilibrium$parameter
  ) 
```

# test market
```{r}
t <- 1
j <- 1
equilibrium$constant$method_s_w <- "exact"
```

# Counterfactual Analysis {.tabset}

## Minimum wage {.tabset}
```{r}
counterfactual <- 
  evaluate_counterfactual_minimum_wage_tj(
    t = t,
    j = j,
    equilibrium = equilibrium,
    solver = "iteration",
    multistart = 20
  )
```

### table 
```{r, results = "asis"}
counterfactual %>%
  dplyr::arrange(
    i,
    minimum_wage
  ) %>%
  kbl() %>%
  kable_styling()
```

### graph {.tabset}
```{r, results = "asis"}
p <- 
  plot_counterfactual_minimum_wage(
    counterfactual = counterfactual
  )
```